version: '3'
services:
  auth_db:
    image: postgres:14.2-alpine
    env_file: ./auth/.env
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file: .env
    ports:
      - 5672:5672
      - 15672:15672

  auth_app:
    build:
      context: ./auth/
    env_file: ./auth/.env
    volumes:
      - ./auth:/code
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  pgdata:
